# -*- coding: utf-8 -*-
"""Trabalho Informática Básica

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zN1PNjQwHUxok_5mCF7AoNJANh-GBlUN
"""

n=int(input('digite um numero para ser convertido em codigo gray'))
x=n
k=[]
while (n>0):
    a=int(float(n%2))
    k.append(a)
    n=(n-a)/2
string=""
for j in k[::-1]:
    string=string+str(j)
string.split()
if len(string)<4:
   for i in range (4-len(string)):
      string= "0"+ string
   a,b,c,d=(string)
else:
   a,b,c,d=(string)
if a=='0':          
  d1=0
elif a=='1':
  d1=1
if b!=a:
  d2=1
else:
  d2=0
if c!=b:
  d3=1
else:
  d3=0
if d!=c:
  d4=1
else:
  d4=0
print(d1, d2, d3, d4)