# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yIlA6DhajywyfhvHnmAud3M_bQ_Zt4jJ

1. Faça um programa que peça o número de horas trabalhadas e o valor da hora de um determinado funcionário. Em seguida, calcule o salário do funcionário. Caso o funcionário tenha trabalhado mais de 200 horas, o salário final é acrescido de 5%. Exemplos de
execução:
"""

htrab = float(input('Insira a quantidade de horas trabalhadas: '))
val = float(input('Insira o valor recebido por hora trabalhada: '))
calc1 = float(htrab*val)
calc2 = float(calc1)*0.05
calc4 = float(calc1+calc2)
if htrab >200:
    float(calc1)
    print('Receberá R$ '+str(calc4)+' trabalhando mais de 200 horas.')
else:
    float(calc2)
    print('Receberá R$ '+str(calc1)+' trabalhando menos de 200 horas.')

"""2. Uma fruteira vende maçãs com 2 preços: R$ 0,30 até 12 unidades e R$ 0,25 acima de 12
unidades. Faça um programa que peça a quantidade de maçãs compradas e calcule e
apresente o valor a ser pago. Exemplos de execução:
"""

maca = int(input('Quantas maçãs foram compradas? '))
calc1 =(maca)*0.30
calc2 =(maca)*0.25
if maca <12:
    print('Como foi comprado menos de 12 maçãs você pagará R$ '+str(calc1))
else:
    print('Pela compra dessas maçãs você pagará R$ '+str(calc2))

"""3. Uma loja vende produtos à vista e a prazo (pagamento 30 dias após a compra). À vista
tem um desconto de 5% e a prazo um acréscimo de 10%. Faça um programa em Python
que peça o preço do produto e a forma de pagamento: 1 para à vista e 2 para a prazo.
Depois apresente o preço final do produto. Exemplos de execução:
"""

rs = float(input('Qual o preço (R$) do produto a ser pago? '))
fpag = input('Se o pagamento for á vista digite 1, se o pagamento for a prazo digite 2. ')
if fpag=='1':
  calc1=float(rs*0.05)-rs
  print('O valor a ser pago á vista é de R$ ',(calc1))
if fpag=='2':
  calc2=float(rs*0.1)+rs
  print('O valor a se pago a prazo é R$ ',(calc2))

"""4. Uma eleição possui 2 candidatos: João da Chape e José da Chape. Faça um programa
que peça o número de votos de cada um e apresente o vencedor ou se houve empate.
"""

vot1 = input('Quantos votos recebeu João da Chape? ') 
vot2 = input('Quantos votos recebeu José da Chape? ')
if vot1 > vot2:
  print('Com '+str(vot1)+' votos João da Chape ganhou a eleição, recebeu mais votos.')
if vot1 < vot2:
  print('Com '+str(vot2)+' votos José da Chape ganhou a eleição, recebeu mais votos.')
if vot1 == vot2:
  print('Os dois receberam a mesma quantidade de votos, houve um empate.')

"""5. Faça um programa que leia 2 números e informe se os mesmos são múltiplos, ou seja, um
divide o outro sem resto.
"""

no1=int(input("digite um numero "))
no2=int(input("digite um numero "))

if (no1 % no2==0) or (no2 % no1==0):
    print("é multiplo")
else:
    print("nao sao multiplos")

"""6. Faça um programa que calcule a duração de um evento qualquer. Para tal, o programa
pede a hora de início e hora de fim (sem os minutos), as horas serão informadas de 0 a 23.
Perceba que um evento pode começar em um dia e acabar em outro. Os eventos nunca
durarão mais de 24 horas. Exemplos de execução:
"""

inicio = int(input('Insira o horário de inicio do evento: '))
fim = int(input('Insira o horário de término do evento: '))
if fim < 0 or fim > 24 or inicio < 0 or inicio > 24:
  print('O valor inserido não é válido.')
elif fim > inicio:
  calculo = fim - inicio
  print('Duração: ', calculo, ' horas.')
elif fim < inicio:
  calculo = (inicio - fim - 24)*-1
  print('Duração: ', calculo, ' horas.')
elif fim == inicio:
  print('Duração: 24 horas.')

"""7. Faça um programa que peça 4 números inteiros. Em seguida, apresente quantos números
informados são negativos e quantos são positivos (considere o 0 como positivo). Exemplos
de execução:
"""

no1=int(input("digite um numero"))
no2=int(input("outro numero"))
no3=int(input("outro numero"))
no4=int(input("outro numero"))
posi=0
nega=0
if no1 >= 0:
    posi=posi+1
else:
    nega=nega+1
if no2 >= 0:
    posi=posi+1
else:
    nega=nega+1
if no3 >= 0:
    posi=posi+1
else:
    nega=nega+1
if no4 >= 0:
    posi=posi+1
else:
    nega=nega+1

print("positivos"+ " : " + str(posi)+ " ; " + "negativos"+ " : " + str(nega))

"""8. Você vai fazer um programa para classificar os competidores segundo as suas posições.
Foram criadas 5 classes: Top 5 (1-5), Top 10 (6-10), Top 20 (11-20), Top 30 (21-30) e Top
100 (outras posições). Faça um programa que peça a posição do competidor e indique a
classe do mesmo
"""

pdc=int(input("qual a sua posição na competição?"))
if pdc == 1:
    print("meus parabens! voce é o ganhador e esta no top 5!!!")
elif pdc>=2 and pdc<=5:
    print("voce ficou no top 5! parabens pelo seu esforço e dedicação!!!")
elif pdc>=6 and pdc<=10:
    print("voce ficou no top 10! uma excelente classificação, continue se dedicando e chegara no top 5!")
elif pdc>=11 and pdc<=20:
    print("voce ficou no top 20! uma boa classificação, mas continue melhorando!!")
elif pdc>=21 and pdc<=30:
    print("voce ficou no top 30!, tem uma otima base, mas precias melhorar")
elif pdc>=31 and pdc<=99:
    print("voce esta no top 100, o que significa que tem uma boa base, mas sempre continue melhorando!")
elif pdc == 100:
    print("voce terminou em ultimo, não desista e continue tentando!")
else:
    print("digite uma posição valida, de 1 a 100")

"""9. Faça um programa que calcule o IMC (índice de massa corporal) do usuário e indique a
classe que ele se encontra: menor que 18,5 (abaixo do peso), até 24,9 (peso normal), até
29,9 (sobrepeso) e acima de 29,9 (obeso). O IMC é calculado da seguinte forma: tendo a
altura em metros como entrada (ALT) e o peso em kilos (PESO), IMC=PESO/(ALT2
).
"""

peso=float(input("digite seu peso em kg"))
alt=float(input("digite sua altura em metros"))
imc=peso/(alt*alt)
print(peso)
print(alt)
print(imc)
if imc<18.5:
    print("voce esta abaixo do peso!")
elif imc>=18.5 and imc<24.9:
    print("voce esta em seu peso normal")
elif imc>=24.9 and imc<29.9:
    print("voce esta em sobrepeso, tome cuidado")
elif imc>=29.9:
    print("voce é obeso, tome medidas urgentemente ou correra serios riscos de ataques cardiacos")

"""10. Sabendo que as faixas etárias para votação são: 18 a 70 anos voto obrigatório; 16, 17 e
acima de 70 anos voto facultativo; outras idades (ou seja, menor que 16 anos) não pode
votar.
"""

idade=int(input("digite sua idade"))
if idade>=18 and idade<=70:
    print("voto obrigatorio")
elif idade<16:
    print("nao pode votar")
elif idade == 16 or idade ==17 or idade>70:
    print("seu voto eh facultativo")