# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZhW7-7VKcsLkhrrN8DuaMhgjq79v5SwM
"""

# 1 - Mostrar na tela o produto entre 28 e 45.
conta = (28*45)
print ('O resultado é',conta)

# 2 - Mostrar a média aritmética entre 3 números passados pelo usuário.
num1 = float(input('Digite um primeiro número: '))
num2 = float(input('Digite um segundo número: '))
num3 = float(input('Digite um terceiro número para mostrar a média aritmética entre o três: '))
calc = (num1+num2+num3)/3
print ('Média: ',calc)

# 3 - Leia um número e mostre seu sucessor e seu antecessor na tela.
num = int(input('Insira um número para mostrar seu sucessor e seu antecessor: '))
print ('Seu antecessor é:',(num-1),' E seu sucessor é:',(num+1))

# 4 - Leia dois números e mostre a soma. Ante do resultado, deverá aparecer a mensagem conforme abaixo:
num1 = float(input('Insira um número: '))
num2 = float(input('Insira um segundo número para ver a soma dos dois: '))
calc = (num1+num2)
print ('Soma:',calc)

#5 - Leia um número e mostre a terça parte deste número.
num = float(input('Insira um número para ser mostrado a terça parte dele: '))
calc = (num/3)
print ('A terça parte de',num,'é:',calc)

# 6 - Faça um algoritmo que converta um montante em real para dólar, para tal peça o valor em real que se deseja converter e a cotação atual.
real = float(input('Insira um valor em Real para ser convertido em Dólar:'))
dolar = float(input('Insira a cotação atual do Dólar: '))
cont = (dolar*real)
print ("O valor",real,"Convertido de real para dólar seria de: ",cont)

# 7 - A máquina 1 produz 1 poste por dia, a máquina 2 produz 3 e a máquina 3 produz 2,5.
# Faça um programa que calcule o número de postes produzidos por esta usina para uma quantidade de dias informada
dia = float(input('Insira certa quantidade de dias para informar quantos postes será produzido: '))
maq1 = (1*dia)
maq2 = (3*dia)
maq3 = (2.5*dia)
calc = (6.5*dia)
print ("Com",dia,"dia a máquina 1 irá produzir",maq1,"postes por dia")
print ("Com",dia,"dia a máquina 2 irá produzir",maq2,"postes por dia")
print ("Com",dia,"dia a máquina 3 irá produzir",maq3,"postes por dia")
print ("Com",dia,"dia a usina irá produzir um total de",calc,"postes")

# 8 - O professor gostaria de ter um algoritmo para calcular a média da disciplina Algoritmos.
# Ele aplica 3 provas, sendo que a primeira tem peso 3, a segunda peso 2 e a terceira peso 5.
prov1 = float(input('Insira a nota da primeira prova: '))
prov2 = float(input('Insira a nota da segunda prova: '))
prov3 = float(input('Insira a nota da terceira prova: '))
calc = (prov1*0.3)+(prov2*0.2)+(prov3*0.5)
print ('Sua média final é ',calc)