# -*- coding: utf-8 -*-
"""Lista Função

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TebqNKeES_bEnz4gBVSRZjP7IsXfTxqv

1- Faça uma função que lê cinco (5) números inteiros digitados pelo usuário e no final imprima esses números ordenados. Guarde os nomes em uma lista para serem ordenados no final.
"""

Aa=[]
for i in range (5):
    print("Insira os numeros: ")
    a=int(input())
    Aa.append(a)
Aa.sort()
print(Aa)

"""2- Encontre os número primos gêmeos entre 1 e 1000, usando uma função para verificar se o número é primo. Primos gêmeos são aqueles que a diferença entre valores primos é igual a 2. Por exemplo, o número 5 e 7 são primos gêmeos.

"""

def primogemeo():
    primos = []
    for c in range(1, 1001):
        soma = 0
        for i in range(1, c):
            if c % i == 0:
                soma += i
        if soma <= 2:
            primos.append(c)
    gemeos = []
    for c in primos:
        a = (6 * c + 1)
        b = (6 * c - 1)
        if a - b == 2:
            gemeos.append(b)
            gemeos.append(a)
    del gemeos[78:]
    print(f"Os números primos gêmeos são: {gemeos}")


primogemeo()

"""3- Escreva uma função que imprima a posição de cada caractere na string.
	EX:”joao”
	Caracter “j” na posição 0
	Caracter “o” na posição 1

"""

def posicaodocaracter():
    palavra = input("Digite a palavra: ")
    for c in range(len(palavra)):
        print(f"Caracter '{palavra[c]}' na posição {c}")


posicaodocaracter()

"""4- Escreva uma Função que que troque as vírgulas por ponto (sem variáveis globais):
Ex: “123.123.132”
      “123,123,123”

"""

def trocar(virgula):
    print(virgula.replace(",", '.'))


string = input("Digite a informação: ")
trocar(string)

"""5 - Faça uma função que receba um número inteiro positivo como parâmetro e retorne 1 ​ se o número em questão é perfeito, ou ​ 0(zero) caso contrário. Um número perfeito é ​aquele cuja soma de todos os seus divisores positivos (excluindo ele mesmo) é igual ao próprio número. Por exemplo, o número 6 é ​ um número perfeito, pois: 6 ​ = 1 + 2 + 3 . ​ O próximo número perfeito é o 28, pois 28 ​ = 1 + 2 + 4 + 7 + 14 . ​

"""

def perfeito(num):
    soma = 0
    for val in range(1, num):
        if num % val == 0:
            soma += val
    if soma == num:
        print("1, é perfeito")
    else:
        print("0, não é perfeito")


num = int(input("Qual número quer saber se é perfeito? "))
perfeito(num)