# -*- coding: utf-8 -*-
"""fim

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rgMe489O9vaJQYpoo4PfakXgn9iv0mnh
"""

import random
def cpf_validate(numbers):
    cpf = [int(char) for char in numbers if char.isdigit()]
    if len(cpf) != 11:
        return False
    if cpf == cpf[::-1]:
        return False
    for i in range(9, 11):
        value = sum((cpf[num] * ((i+1) - num) for num in range(0, i)))
        digit = ((value * 10) % 11) % 10
        if digit != cpf[i]:
            return False
    return True

class cliente:
  nome=""
  sobrenome=""
  CPF=0
  senha=""
  limite=0
  limite1=0
  ncartao=""
  cr=0
  compras=[]
class compraclient:
  compracartao=''
  loja=""
  valor=0
  data=''

CPFF=[]
compras=compraclient()
clientes=cliente()
cadastros=[]
comprinhas=[]
#while True :
#  robo=input("Digite o código a seguir abaixo: #SsKoo!@ \n ")
#  if robo=="#SsKoo!@":
#    print("Ok, continue, tava apenas te testando")
#    break
#  else:
#4    print("Tente novamente!")
    
while True:
  
  print('---------------------')
  print("Escreva o que você deseja fazer: ")
  print('---------------------')
  fazer=int(input(" 1 - Cadastro Cliente \n 2 - Login (Compras, faturas e aumento do limite)   \n 3 - Lista de Clientes \n 4 - Extrato geral \n 5 - Sair \n "))
  print('---------------------')

  if fazer==1:
    clientes.nome=input('Digite seu nome: ')
    clientes.sobrenome=input('Digite seu sobrenome: ')
    while True:
      clientes.CPF= str(input('Insira seu CPF: '))
      if cpf_validate(clientes.CPF)==False:
        print('CPF inválido')
      elif clientes.CPF in CPFF:
        print('Esse CPF ja possui cadastro.')
      else:
        CPFF.append(clientes.CPF)
        break
    while True:
      for i in range(16):
        n=str(random.randint(1,9))
        clientes.ncartao+=n
      
      if clientes.ncartao not in cadastros:
          print('O número do seu cartão é:', clientes.ncartao)
          break
    while True:
      clientes.senha=str(input('Insira uma senha com 6 dígitos: '))
      if len(clientes.senha)!=6:
        print('Senha inválida, insira uma senha com apenas 6 dígitos')
      else:
        senha1=(input('Confirme sua senha digitando ela de novo: '))
        if senha1 != clientes.senha:
          print('As senhas não coincidem, tente novamente')
        else:
         break
    renda=float(input("Digite sua renda para estipularmos um limite: "))
    if renda>=1249997:#as pessoas que possuirem renda 1249997 ou mais terao seu limite de 999999(80% de 1249997) que é o valor maximo permitido no limite
      clientes.limite=999999
      cliente.limite1=999999
    elif renda<=500:#para pessoas com renda ugual ou inferior a 500 reais terao um limite padrao de 250.
      clientes.limite=250
      clientes.limite1=250
    else:
      clientes.limite=renda-(renda*0.2)#o limite do cartao é 80% da renda da pessoa.
      clientes.limite1=renda-(renda*0.2)
    print("seu limite R$", clientes.limite)

    while True:
      usuarioroot = input('Insira a senha Root para obter acesso: ')
      if usuarioroot != "joigor#":
        print('Senha Root errada!')
      else:
        break
    cadastros.append(clientes)
    comprinhas.append(compras)
    compras=compraclient()
    clientes=cliente()
    print("\n CONTA CRIADA COM SUCESSO! ")
  
  elif fazer==2:            #inicia a aba do cliente
    while True:
      print("PARA FAZER LOGIN DIGITE O NUMERO DO CARTAO E A SENHA:(PARA SAIR DIGITE 0) ")
      logincar=input("Número do cartão: ")
      if logincar=='0':
        break
      loginsen=input('Digite sua senha: ')
      for i in cadastros:
        if logincar==i.ncartao and loginsen==i.senha:
          nc=i
          logincar=compras.compracartao
          print("Login feito com sucesso! Bem vindo a sua conta", i.nome, i.sobrenome)
          print("---------------------")
          while True:
            dec=input("Digite o que você deseja fazer:\n 1 - Fazer compras \n 2 - Pagamento fatura \n 3 - Pedir aumento de limite \n 4 - Sair da conta \n")
            if dec=="1":
              print("---------------------")
              while True:
                compras=compraclient()
                v=int(input("Digite o valor da compra: "))
                if v>i.limite:
                  print("Limite insuficiente para realizar essa compra, pague sua fatura. ")
                  break
                compras.valor+=v
                i.limite=i.limite-v
                while True:
                  d=input("Digite a data da compra no formato DD/MM/AAAA: ")
                  if len(d) != 10:
                    print('Digite uma data válida no formato DD/MM/AAAA')
                  else:
                    break
                l=input("Digite a loja: ")
                compras.loja+=l
                comprinhas.append(compras)
                compras=compraclient()
                print(i.limite)
                break

            elif dec=="2":
               deve=i.limite1-i.limite
               print("Você esta devendo R$", deve, "reais")
               print("---------------------")
               pag=float(input("Digite o valor que você deseja pagar, se você nao quiser pagar digite 0,"))
               if pag>deve:
                 i.limite=i.limite1
                 print("Você digitou um valor acima do que você deve, mas só foi contabilizado R$", deve, "reais")
                 i.cr+=1 #credito para aumentar limite
                 
               elif pag==deve:
                 i.limite=i.limite1
                 print("Obrigado por usar o CCbank e pagar sua fatura em dia!")
                 i.cr+=1 
               elif pag<deve:
                 i.limite+=pag
                 print("Você pagou R$", pag, "e sua fatura era R$", deve, ", você ainda deve R$", float(deve-pag), "e seu saldo disponível é R$", i.limite)
               clientes=cliente()   
               cadastros.append(clientes)

            elif dec=="3":
              if i.cr>=12:
                print("---------------------")
                alimento=input("Você pode aumentar seu limite em 10%, deseja aumentar?(Digite S/N)").upper()
                if alimento=="S":
                  if i.limite1-i.limite>0:
                    print("para aumentar o limite primeiro pague sua fatura.")
                  else:
                    i.limite1= i.limite1*1.10
                    print("seu limite foi aumentado, ele agora é de: R$", i.limite1, "Reais.")
                else:
                  print("Ok, caso mude de ideia fale conosco! ")
              else:
                print("---------------------")
                print("Você não tem créditos suficientes para pedir aumento de limte. ")
            elif dec=="4":
              break
  elif fazer==3:
    while True:
      root=input("Digite a senha root para poder ter acesso aos clientes ")
      print("---------------------")
      if root=="joigor#":
        for k in cadastros:
          print("Nome: ", k.nome, k.sobrenome,"CPF: ", k.CPF, "Número do cartão: ", k.ncartao)
        break
      else:
        print("Senha root incorreta, tente novamente. ")
  elif fazer == 4:
    while True:
      r=input("Digite a senha root para ter acesso ao extrato geral. ")
      print("---------------------")
      if r=="joigor#":
        for j in comprinhas:
          if compras.compracartao==j.compracartao:
            print("Valor: ", j.valor, "Data da compra: ", j.data, "Loja da compra:", j.loja)
        break
      else:
        print("Senha root incorreta, tente novamente ")      
  elif fazer==5:
   break

